# Quick Dash score
to assess whethere movement quality is related to patient reported functioning. 
We expect that movement quality post-operatively is related to patient reported disability and pain scores. 
And that there are differences in movement quality between the people with a DASH < 15 and those above 15. The threshold of 15 is chosen because this indicates whether someome is 'disabled' or not

1) Only retain t1 (1 months post-op data) 
and remove participants with to many NaN

2) Calculate the total DASH score

Berekening Quick DASH beperkingen en symptomen score:  
{(Som van de antwoorden op N items / N ) â€“ 1} x 25 
N = aantal ingevulde antwoorden  
Let op: de Quick DASH score mag niet berekend worden als meer dan 1 vraag niet beantwoord is.


3) Split group on disabled group and non-disabled

4) Correlate the Quick Dash scores with movement quality. i.e. do people with a higher score perform better?

In [46]:
import numpy as np
import pandas as pd

#### Input data sets
1) Dash scores

In [47]:
raw = pd.read_csv("C:\\Users\\u0117545\\KU Leuven\\An De Groef - DATA\\XsensTest\\QuickDASH\\UPLIFTBC-QuickDASH_DATA_2022-10-31_1406 (1).csv",
                   sep=';')

In [48]:
# only retain T1 of the dash scores 
idx = raw['redcap_event_name'].str.contains('t1')
mask = np.where(idx)[0]
raw = raw.iloc[mask]
raw.head()

,record_id,redcap_event_name,quickdash_1,quickdash_2,quickdash_3,quickdash_4,quickdash_5,quickdash_6,quickdash_7,quickdash_8,quickdash_9,quickdash_10,quickdash_11
1,BC_001,t1_1_month_postsur_arm_1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
4,BC_002,t1_1_month_postsur_arm_1,2.0,3.0,1.0,3.0,1.0,3.0,1.0,2.0,2.0,1.0,1.0
6,BC_003,t1_1_month_postsur_arm_1,2.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0
9,BC_005,t1_1_month_postsur_arm_1,3.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,3.0,3.0,3.0
11,BC_006,t1_1_month_postsur_arm_1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [49]:
# remove participants with more than 2 NaNs
# Remove rows with missing values
print("Before removing rows with missing data: {} rows".format(len(raw)))
df_dash = raw.dropna(thresh=raw.shape[1]-1, axis=0)
print("After removing rows with missing data: {} rows".format(len(df_dash)))

Before removing rows with missing data: 21 rows
After removing rows with missing data: 15 rows

2) Movement quality parameters

In [50]:
df_qual = pd.read_excel('C:/Users/u0117545/Documents/GitHub/ULIFT_BC/Output/MoveQual_aff.xlsx', sheet_name = 'T1')
df_qual.head()

,ppID,trial,time,lyapExp_x,lyapExp_y,lyapExp_z,lyapExp_res,sampen_x,sampen_y,sampen_z,...,rms_z,rms_res,rmsr_x,rmsr_y,rmsr_z,sparc_x,sparc_y,sparc_z,sparc_res,LDLJ_A
0,BC_001,F_R_001,T1,7.701734,8.671551,1.385935,6.587047,0.188650,0.639654,0.117585,...,0.951799,1.301812,0.509471,0.336057,0.792152,-4.924341,-3.823578,-5.195009,-2.826718,-8.804562
1,BC_002,F_L_001,T1,4.819965,2.955782,4.651802,3.021216,0.902024,1.048165,0.832677,...,2.338018,3.361040,0.529273,0.415402,0.739805,-3.635514,-2.818207,-3.670352,-2.103190,-7.668037
2,BC_003,F_R_001,T1,2.935410,1.640538,3.245344,4.049951,0.549589,1.416456,0.435703,...,4.132086,6.322299,0.435838,0.582890,0.685773,-2.999487,-2.863180,-3.500903,-1.937020,-7.086592
3,BC_005,F_R_001,T1,3.296498,2.138640,2.523334,2.579761,1.070558,1.219464,0.610133,...,2.782943,3.787381,0.516137,0.354723,0.779599,-4.989269,-2.960899,-3.663430,-2.240403,-7.479738
4,BC_006,F_R_001,T1,2.100760,1.943798,2.159363,5.518124,0.369269,0.757041,0.292400,...,2.455728,3.444624,0.563278,0.304754,0.768013,-8.440110,-2.915060,-3.413227,-2.345322,-8.140653

#### Calculate total dash scores

In [51]:
som = df_dash.iloc[:,2:].sum(axis='columns')
col_n_counts = np.sum(df_dash.applymap(lambda x: 0 if pd.isnull(x) else 1), axis=1)-2
complete = col_n_counts.apply(lambda x:  x >= 10 )

total_score = ((som/col_n_counts)-1) * 25

print('Average score over all participants and timepoints = {}'.format(np.mean(total_score)))
print('Maximum and minumum scores are {} & {} respectively'.format(total_score.max(), total_score.min()))

Average score over all participants and timepoints = 26.363636363636363
Maximum and minumum scores are 70.45454545454545 & 0.0 respectively

In [52]:
#set-up dataframe for total dash scores. 
d = {'ppID': df_dash['record_id'],
    'total_score': total_score}
df_totaldash = pd.DataFrame(data=d)

In [53]:
# merge the dataframes on ppID remove time and trial (since it is all 1 months post op)
# use df for all furhter analysis
df = df_totaldash.merge(df_qual)
df = df.drop(labels=['trial', 'time'], axis = 1)
df.head()

,ppID,total_score,lyapExp_x,lyapExp_y,lyapExp_z,lyapExp_res,sampen_x,sampen_y,sampen_z,sampen_res,...,rms_z,rms_res,rmsr_x,rmsr_y,rmsr_z,sparc_x,sparc_y,sparc_z,sparc_res,LDLJ_A
0,BC_001,0.000000,7.701734,8.671551,1.385935,6.587047,0.188650,0.639654,0.117585,0.201132,...,0.951799,1.301812,0.509471,0.336057,0.792152,-4.924341,-3.823578,-5.195009,-2.826718,-8.804562
1,BC_002,20.454545,4.819965,2.955782,4.651802,3.021216,0.902024,1.048165,0.832677,0.973957,...,2.338018,3.361040,0.529273,0.415402,0.739805,-3.635514,-2.818207,-3.670352,-2.103190,-7.668037
2,BC_003,15.909091,2.935410,1.640538,3.245344,4.049951,0.549589,1.416456,0.435703,0.520216,...,4.132086,6.322299,0.435838,0.582890,0.685773,-2.999487,-2.863180,-3.500903,-1.937020,-7.086592
3,BC_005,29.545455,3.296498,2.138640,2.523334,2.579761,1.070558,1.219464,0.610133,0.914877,...,2.782943,3.787381,0.516137,0.354723,0.779599,-4.989269,-2.960899,-3.663430,-2.240403,-7.479738
4,BC_006,0.000000,2.100760,1.943798,2.159363,5.518124,0.369269,0.757041,0.292400,0.383689,...,2.455728,3.444624,0.563278,0.304754,0.768013,-8.440110,-2.915060,-3.413227,-2.345322,-8.140653

#### 3) Split group on disabled group and non-disabled

In [67]:
# find the people with a dash score higher than 15
idx = df['total_score'] >= 15
mask = np.where(idx)[0]
pain = df.iloc[mask]

# find the people with a dash score lower than 15
idx = df['total_score'] < 15
mask = np.where(idx)[0]
no_pain = df.iloc[mask]
no_pain

print('number of people with perceived disablity: {}'.format(len(pain)))
print('number of people with no perceived disablity: {}'.format(len(no_pain)))

number of people with perceived disablity: 9
number of people with no perceived disablity: 6